1011=OK
1012=
1013=
1014=
3001=Bad URI.
3011=Bad action.
3012=No connection.
3013=No document.
3014=Authentication failure.
3015=Bad request.
3016=No result.
3017=This session is already transcoding. Wait until it finishes.
4001=Unxexpected error.